name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install Node dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install Composer dependencies
        working-directory: ./api
        run: |
          # Install dependencies
          composer install --no-dev --no-progress
          
          # Create TCPDF config directory and copy default config
          mkdir -p vendor/tecnickcom/tcpdf/config
          cp vendor/tecnickcom/tcpdf/config/tcpdf_config_alt.php vendor/tecnickcom/tcpdf/config/tcpdf_config.php
          
          # Optimize autoloader
          composer dump-autoload --optimize

      - name: Copy API files
        run: |
          mkdir -p build/api
          cp -r api/* build/api/
          cp .htaccess build/
          
          # Remove unnecessary files from build
          rm -rf build/api/vendor/*/test/
          rm -rf build/api/vendor/*/tests/
          rm -rf build/api/vendor/*/docs/
          rm -rf build/api/composer.*
          
          # Ensure TCPDF config directory exists in build
          mkdir -p build/api/vendor/tecnickcom/tcpdf/config

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"